# SIGNAL app
# edits February, 2021
#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#
options(scipen = 999)
library(shiny)
library(shinyjs)
library(shinyBS)
library(shinyWidgets)
# library(shinyMatrix)
library(readr)
library(dplyr)
library(stringi)
library(DT)
library(data.table)
library(igraph)
library(edgebundleR)
library(shinyAce)
#library(rJava)
#library(mailR)
library(networkD3)
library(visNetwork)
library(org.Hs.eg.db)
library(org.Mm.eg.db)
library(GO.db)
library(AnnotationDbi)
library(reshape2)
library(ggplot2)
library(tidyr)
library(gridExtra)
library(crosstalk)
library(htmltools)
library(stringr)
library(tools)
library(readxl)
library(fgsea) #For the fora fast pckage

Sys.setenv(R_ZIPCMD="/usr/bin/zip")

### TO RUN LOCALLY ###
# Assign the home_string for folder where SIGNAL has been downloaded to
# home_string = '/Users/username/SIGNAL-folder'
# Sys.setenv(HOME = home_string)
# setwd('~')

### Package check and installation (for local development)
# L = c('shiny', 'shinyjs', 'shinyBS', 'readr', 'dplyr', 'stringi', 'DT', 'data.table',
#       'igraph', 'edgebundleR', 'shinyAce', 'networkD3', 'visNetwork',
#       'AnnotationDbi', 'reshape2', 'ggplot2', 'tidyr', 'gridExtra', 'crosstalk', 
#       'htmltools', 'stringr', 'org.Hs.eg.db', 'org.Mm.eg.db', 'mailR', 'rJava')
# 
# package.check <- lapply(L, FUN = function(x) {
#   if (!require(x, character.only = TRUE)) {
#     if(x != 'org.Hs.eg.db' & x != 'org.Mm.eg.db'){
#       install.packages(x, dependencies = TRUE)
#       library(x, character.only = TRUE)
#     }
#     else{
#       if("BiocManager" %in% installed.packages()){
#         BiocManager::install(x, version = "3.8")
#       }
#       else{
#         install.packages("BiocManager")
#         BiocManager::install(x, version = "3.8")
#       }
#     }
#   }
# })

### Errors with rJava ###
# If running a mac and having trouble loading rJava - follow the steps on this site:
# https://zhiyzuo.github.io/installation-rJava/
# If running a pc and having trouble loading rJava:
# https://www.r-statistics.com/2012/08/how-to-load-the-rjava-package-after-the-error-java_home-cannot-be-determined-from-the-registry/

#setting
#override scientific notation to avoid numeric mis assignments
options(scipen = 999)

# global variables
organism <- NULL
organismAbbr <- NULL
originalHits <- NULL
networkType <- NULL

### SIGNAL veriosn
SIGNAL.version <- "Version 1.0"
SIGNAL.update.date <- "November 20, 2020"

### Database versions
KEGG.version <- "2020"
KEGG.update.date <- "November 20, 2020"

STRING.version <- "11.0"
STRING.update.date <- "November 20, 2020"


# Function to validation email addresses
isValidEmail <- function(x) {
  grepl("\\<[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}\\>", as.character(x),
        ignore.case=TRUE)
}

# Set the maximum input file size to 10Mb
options(shiny.maxRequestSize = 10*1024^2)

# Global environmental variables
envs <- Sys.getenv()
env_names <- names(envs)

## Set up dataDir
if('SHINY_SERVER_VERSION' %in% env_names){
  dataDir <- '/srv/shiny-server/data/'
}else{
  #TODO - see if this needs changing. Currently only version working on runApp
  #dataDir <<- paste0(getwd(), "/data/")
  dataDir <<- "~/SIGNAL/app/data/"
}

## Set up downloadDir
if('SHINY_SERVER_VERSION' %in% env_names){
  outputDir <- '/srv/shiny-server/inputOutputs/SIGNALoutputFiles/'
}else{
  outputDir <- "~/SIGNAL/app/inputOutputs/SIGNALoutputFiles/"
}
userDir <- format(Sys.time(),"%Y%m%d%H%M%S%ms")
outDir <<- paste0(outputDir, userDir)
dir.create(outDir, showWarnings = TRUE, recursive = TRUE, mode = "0777")
print(paste0(outputDir, " created"))
downloadDir <<- paste0(outDir, "/", "SIGNALfilesToDownload")
currentDir <- getwd()
dir.create(downloadDir)
print(paste0(downloadDir, " created"))
setwd(downloadDir) 


## Complete list of all protein-encoding genes in human genome
## ftp://ftp.ebi.ac.uk/pub/databases/genenames/new/tsv/locus_types/gene_with_protein_product.txt
humanGenes <- read.table(file=paste0(dataDir, "HGNC_genes_with_protein_product_EntrezID_geneSymbole_lookup.txt"), sep="\t", header=TRUE)

## Complete list of all genes in mouse genome
## http://www.informatics.jax.org/downloads/reports/MGI_Gene_Model_Coord.rpt
mouseGenes <- read.table(file=paste0(dataDir, "Mouse_genes_with_protein_product_EntrezID_geneSymbol_lookup.txt"), sep="\t", header=TRUE)

## The two files used above can be updated/regenerated by runing the Rscript 
## 'Generate_human_and_mouse_protein_codig_genes_for_SIGNAL.R' in the Rscripts folder


########### Holding facility - to be used later as needed
#pre-loading to save time
#GO_Offspring <- as.list(GOBPOFFSPRING)

#To convert GO list to df of given format

# genes_as_df <- map_dfr(names(xx), function(x) {
#   all_genes = xx[[x]]
#   out = data.frame(
#     path = rep(x, length(all_genes) ),
#     gene = unname(all_genes)
#   )
#   return(out)
# } )
# 

#Converts entrezid to symbol name
#select(org.Hs.eg.db, keys = '1234', columns = c('ENTREZID', 'SYMBOL'), keytype = 'ENTREZID')
