format_version: 2

pipelines:

    Triage_Build_DeployQA_Scan:
        group: LSB_triage
        label_template: ${COUNT}_${app-repo[:7]}
        lock_behavior: unlockWhenFinished
        materials:
            app-repo:
                git: git@github.niaid.nih.gov:yazhuks2/TRIAGE.git
            base-image:
                pipeline: shiny1-ubuntu18.04
                stage: Build
        environment_variables:
            PIPELINE_ENABLE: true
            IMAGE_LOCATION: .
            IMAGE_NAME: triage
            IMAGE_REPO: lsb-triage
            REGISTRY_USER: songj11
        secure_variables:
            REGISTRY_PASS: Eq1ailPp4vUXP+LYw3Zg62MQEcwCvlALis2i1hryHBF4OXZs9e7xLS7LSroMiMKw+LnKyHhQ4JultE37H/wytCVM2+rT90XdVhin7ljhK9c=
        template: Build_DeployQA_Scan_OnPrem
        parameters:
            UPSTREAM_DOCKER_PIPELINE: shiny1-ubuntu18.04

    Triage_Promote_DeployProd:
        group: LSB_triage
        label_template: ${Triage_Build_DeployQA_Scan}
        lock_behavior: unlockWhenFinished
        materials:
            build-deploy_qa-scan:
                pipeline: Triage_Build_DeployQA_Scan
                stage: Scan_and_Test
        environment_variables:
            PIPELINE_ENABLE: false
        parameters:
            MY_UPSTREAM_SCAN_PIPELINE: Triage_Build_DeployQA_Scan
            MY_UPSTREAM_DOCKER_PIPELINE: Triage_Build_DeployQA_Scan
